### ISSUE TITLE
Is it possible to trigger Browse... window by clicking a link?

### ISSUE THREAD

**Issue by raunom** [cotag/a2-file-drop#3]
Hi,

Thanks for the plugin -- I have been trying some different Angular2 drag-and-drop file upload plugins for couple of days (I must say there's not too many) and yours is pretty nice :)

There is one question though -- is it possible to trigger Browse... window by clicking a link? I mean it is nice to drag-and-drop files, but sometimes it's easier for some users to just click the link and browse for files.

Any hints or suggestions...? Thanks.

**Comment by stakach** [comment]
Example in the readme:


### File Input Directive

1. Include the directive in your Component or Directive
     * `import {FileStream} from 'a2-file-drop/dist/file-stream';`
2. Add the directive to the target elements
     * `<input type="file" multiple file-stream="media-uploads">`


If you want it to look like a link you have to do some pretty hacky CSS stuff, it is possible though
