### ISSUE TITLE
Not working in Safari

### ISSUE THREAD

**Issue by santimoral** [cotag/a2-file-drop#4]
When used in Safari you get an error in the console:

Error: eval@[native code] eval code eval@[native code] eval code eval@[native code] eval code eval@[native code] eval code eval@[native code] invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:232:31 run@http://localhost:3000/node_modules/zone.js/dist/zone.js:114:49 http://localhost:3000/node_modules/zone.js/dist/zone.js:502:60 invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:265:40 runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:154:57 drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:401:42 g@http://localhost:3000/node_modules/core-js/client/shim.min.js:8:10017 http://localhost:3000/node_modules/core-js/client/shim.min.js:8:10139 k@http://localhost:3000/node_modules/core-js/client/shim.min.js:8:14294 Evaluating http://localhost:3000/node_modules/a2-file-drop/dist/drop-service.js Evaluating http://localhost:3000/app/common/image-upload.js Evaluating http://localhost:3000/app/common/index.js Evaluating http://localhost:3000/app/app.module.js Evaluating http://localhost:3000/app/main.js Error loading http://localhost:3000/app/main.js

**Comment by stakach** [comment]
We've actually merged this project into another:
https://github.com/acaprojects/a2-widgets/ - documentation here is still good however some file paths have changed

Might be worth checking if the newer version works and I'll update the readme here soon.

Otherwise I'm pretty flat out for the next week or so

**Comment by santimoral** [comment]
Thank you for the answer. It seems that the problem is only happening in my machine. Your component set looks really amazing, I will have a look.
